#Alg Configs:


Signal_configs:
  #是否进行保存信号原始数据，0表示不保存，1表示保存
  save_txt: 0

  #上位机软件数据分析展示到最大太赫兹数，默认3
  thz_max: 6

  #每次上位机软件重启是否重置滤波，默认重置为0，不重置设置为1
  filter_restart: 0

  #滤波类型
  filter_type: 0

  #太赫兹时域信号卷积滤波消除周期性震荡，0表示关闭，1表示开启
  open_cov: 1

  #卷积滤波首尾消除，默认不消除为0，消除设置为1
  cov_noise: 0

  #是否对信号进行Savitzky-Golay滤波处理，默认值为0不进行滤波，1为进行浅度去毛刺，2为进行深度去毛刺
  SG: 0

  #是否对信号进行中值滤波处理消除毛刺噪声，默认值为0不进行滤波，其他值必须设置为奇数才进行中值滤波
  medianf: 7

  #是否对信号进行带通滤波处理，选择类型bandpass，lowpass，highpass，不开启填写none
  filter_name: lowpass

  #是否对信号进行带通滤波处理，滤波的使用阶数，范围1-8，默认值为6
  butter_order: 4.0

  #是否对信号进行低通滤波处理消除低频噪声
  lowpass_value: 0.1

  #是否对信号进行高通滤波处理消除高频噪声
  highpass_value: 0.8

  #是否对信号进行小波滤波处理，默认值为0不进行滤波，1进行小波变换
  dwt: 1

  #是否对信号进行小波滤波处理，在上述值为1下生效，小波变换例如：db13, db25, db31, sym11, sym13, coif17,  ......，选择其中之一。
  wave_name: haar

  #小波去噪的阶数
  wave_level: 5

  #小波去噪的方法soft或者hard
  wave_threshold: soft

  #反卷积类型
  dev_mode: DGIF

  #反卷积滤波参数
  DGIF_LF: 0.24
  DGIF_HF: 0.56

  #反卷积参考信号路径
  dev_path: D:\THZ_data\data.xls

  #切比雪夫滤波器
  fp: 2.0
  fs: 10.0
  rp: 4.0
  rs: 5.0
  Fs: 50.0

  #是否对信号进行主峰对齐，如果要对齐则修改下面参数为1，如果不对齐则默认参数为0.
  align_signal: 0

  #是否对频谱进行归一化，默认不进行归一化，如果要归一化设置参数为1
  fre_scale: 1

  #是否显示滤波，0表示不显示滤波后信号，1表示显示
  show_filter: 0

  #垂直入射镜头消除反射峰，默认关闭为0，打开为1
  move_second: 0

  #反射峰间隔阈值,间隔峰时间值
  t_thresh: 42
  t_second: 44




Imaging_configs:
  #参数0显示的是xy截面、xz截面、yz截面都是正向
  #参数1显示的是xy截面、xz截面、yz截面都是左右反向
  #参数2显示的是xy截面、xz截面、yz截面都是上下反向
  #参数3显示的是xy截面、xz截面、yz截面左右上下全反向
  #参数4显示的是xy截面、xz截面、yz截面都是逆时针差90度
  #参数5显示的是xy截面、xz截面、yz截面逆时针差90度后左右反向
  #参数6显示的是xy截面、xz截面、yz截面逆时针差90度后上下反向
  #参数7显示的是xy截面、xz截面、yz截面都是顺时针差90度
  #参数8显示的是xy截面、xz截面、yz截面顺时针差90度后左右反向
  #参数9显示的是xy截面、xz截面、yz截面顺时针差90度后上下反向
  xy: 0
  xz: 2
  yz: 2

  #三维层析成像信号进行删除小于步进的点，取值范围为0.1-0.5，默认值为0.5，在采集点数少的情况下请改为0.1。
  delete_d: 0.1

  #三维层析成像信号显示是否加入中值滤波与小波变换，0表示不加滤波，1表示加滤波
  filterD: 0

  #三维层析成像信号中值滤波参数，此数值必须为奇数，若不为奇数将默认为15,此功能只有在上面滤波值为1才生效。
  filternum: 15

  #三维层析成像对信号阈值高低截断处理，默认值为0，当值为1时下面两个高低截断功能才生效。
  use_threshold: 0

  #三维层析成像显示进行信号阈值截断，阈值默认大小为-10000，即所有三维信号大于-10000的保留，小于-10000的删除。
  min_threshold: -10000

  #三维层析成像对信号高于某阈值的信号进行置零，默认值为10000，即高于10000的信号置零，低于10000的信号保留
  max_threshold: 10000

  #三维层析成像是否启用层析功能，如果启用设置值为1，如果不启用设置为0，默认值为1。
  use_mayavi: 1

  #三维层析成像是否使用qda数据，如果启用设置值为1，如果不启用设置为0，默认值为0。
  use_qda: 0

  #三维层析成像是否使用qda/fits数据的路径，路径不能有空格。
  qda_path: C:\thztools\thz\tadpole.fits

  #三维层析成像旋转延迟线是否进行对齐，对齐设置为1，默认为0不对齐。
  use_align: 0

  #是否解析旋转延迟线,默认0关闭，1为开启。
  roll_delay: 0

  #三维层析成像需要输入参考信号，参考信号以上位机保存的Excel数据为准，第一列为时间列，第二列为参考信号，路径不能有空格。
  ref_path: G:\THZ_Data\data.xls


System_configs:
  #目前二维扫描平台有两种，一种是自研二维平台，二是卓列汉光平台，不同平台成像会出现反向问题。
  #在此加入配置文件进行选择调用。1代表自研二维平台，2代表卓列汉光。修改参数进行配置。
  platform: 1

  #新移动平台精度是旧平台的两倍,旧平台精度设置为1，新平台精度设置为2
  precision: 2

  #只取延迟线正向采集数据标记为0，只取延迟线反向采集数据标记为1，延迟线正向反向采集数据都要标记为2
  delay_line: 0

  #延迟线长度参数配置
  delay_length: 0.5

  #旋转延迟线几倍光程参数配置
  shine_length: 6

  #获取THZ进程
  THZ: 55516


Classification_configs:
  #物质识别：参考信号, L酪氨酸, L精氨酸, L色氨酸
  samples_cla: 空载信号, DL酪氨酸, L酪氨酸, L亮氨酸, L缬氨酸, 滑石粉,邻苯二甲酸氢钾, 卡马西平片, 司乐平, 苯甲酸,甜蜜素, 香兰素, 山梨酸

  #是否进行物质分类，1表示开启，0表示关闭
  classification: 1

  #是否进行蛋白质物质分类，1表示开启，0表示关闭
  protein_classy: 0

  #物质识别特征长度190,229,349
  width_cla: 190


Email_configs:
  #笔记本电脑的camera为参数1，台式机的camera为参数0
  num_camera: 1

  #0表示不存储图像，1表示存储图像
  save_camera: 0

  #左上角坐标
  toplx: 141.97
  toply: 73.94

  #右上角坐标
  toprx: 496.16
  topry: 77.86

  #左下角坐标
  downlx: 90.87
  downly: 360.04

  #右下角坐标
  downrx: 538.05
  downry: 365.99

